### ISSUE TITLE
[Nukkit 2.0] Player join issue

### ISSUE THREAD

**Issue by Alemiz112** [CloudburstMC/Server#12]
This happens when player tries to join server.
```
[ForkJoinPool-1-worker-2] WARN  - Unable to load chunk (2, 3) in level world 
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Palette contains same block state twice!
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalArgumentException: Palette contains same block state twice!
	at cn.nukkit.level.chunk.BlockStorage.readFromStorage(BlockStorage.java:164) ~[nukkit-2.0-SNAPSHOT.jar:?]
	at cn.nukkit.level.provider.leveldb.serializer.ChunkSectionSerializerV8.deserialize(ChunkSectionSerializerV8.java:32) ~[nukkit-2.0-SNAPSHOT.jar:?]
	at cn.nukkit.level.provider.leveldb.serializer.ChunkSectionSerializers.deserialize(ChunkSectionSerializers.java:28) ~[nukkit-2.0-SNAPSHOT.jar:?]
	at cn.nukkit.level.provider.leveldb.serializer.ChunkSerializerV3.deserialize(ChunkSerializerV3.java:86) ~[nukkit-2.0-SNAPSHOT.jar:?]
	at cn.nukkit.level.provider.leveldb.serializer.ChunkSerializers.deserializeChunk(ChunkSerializers.java:44) ~[nukkit-2.0-SNAPSHOT.jar:?]
	at cn.nukkit.level.provider.leveldb.LevelDBProvider.lambda$readChunk$0(LevelDBProvider.java:71) ~[nukkit-2.0-SNAPSHOT.jar:?]
```
Full error [here](https://paste.sh/I4aTcNwc#Of8rthz0ClgvqMtPN7TVUhmB).

**Comment by Kazzuk** [comment]
Resolved by https://github.com/CloudburstMC/Cloudburst/commit/d2dbb4b32dc43d74777ae85b9726eb44ee6305e1
