### ISSUE TITLE
Plugins Crash The Server

### ISSUE THREAD

**Issue by Jaantheman** [CloudburstMC/Server#44]
### Expected Behavior

When I run the server I expected the server to say "Done" 

### Actual Behavior

It Crashed

### Steps to Reproduce

Try this:
 1. Install The server Software
 2. Add Any plugin
3. Start Server
 

### Debug information

* Debug link:12:58:07 [INFO ] ---- Server status ----
12:58:07 [INFO ] Uptime: 0 days 0 hours 0 minutes 31 seconds
12:58:07 [INFO ] Current TPS: 20.0
12:58:07 [INFO ] Load: 2.89%
12:58:07 [INFO ] Network upload: 0.0 kB/s
12:58:07 [INFO ] Network download: 0.0 kB/s
12:58:07 [INFO ] Thread count: 14
12:58:07 [INFO ] Used memory: 57.7 MB. (3.2%)
12:58:07 [INFO ] Total memory: 218.5 MB.
12:58:07 [INFO ] Maximum VM memory: 1803.0 MB.
12:58:07 [INFO ] Available processors: 4
12:58:07 [INFO ] Players: 0 online, 20 max.
12:58:07 [INFO ] World "world": 0 chunks, 0 entities, 0 blockEntities. Time 0.0ms
12:58:07 [INFO ] World "nether": 0 chunks, 0 entities, 0 blockEntities. Time 0.0ms
* Timings link (if relevant):

### Crashdump, Backtrace or Other Files

I need help with HasteBin

but here is crash report2020-08-17 12:32:53.338 [main] INFO  - Loading §anukkit.yml§f ...
2020-08-17 12:32:53.379 [main] INFO  - Loading §aserver.properties§f ...
2020-08-17 12:32:53.423 [main] INFO  - language.selected
2020-08-17 12:32:53.571 [main] INFO  - Starting Minecraft: Bedrock Edition server version §b1.16.20§r
2020-08-17 12:32:53.581 [main] INFO  - This server is running Nukkit version §egit-cc05e40§f "§b§f" (API 2.0.0)
2020-08-17 12:32:53.581 [main] INFO  - Nukkit is distributed under the GPL License
2020-08-17 12:32:54.280 [main] INFO  - Loading recipes...
2020-08-17 12:32:54.661 [main] INFO  - Loaded 1625 recipes.
2020-08-17 12:32:54.712 [main] ERROR - Could not load plugin 'CustomRecipes': Incompatible API version
2020-08-17 12:32:54.725 [main] ERROR - Could not load plugin 'FastAsyncWorldEdit': Incompatible API version
2020-08-17 12:32:54.728 [main] ERROR - Could not load plugin 'ItemBlacklist': Incompatible API version
2020-08-17 12:32:54.731 [main] INFO  - Loading CustomRecipes v1.0.0-SNAPSHOT
2020-08-17 12:32:54.734 [main] FATAL - Nukkit crashed
java.lang.NoClassDefFoundError: cn/nukkit/plugin/PluginBase
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_242]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757) ~[?:1.8.0_242]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_242]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_242]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_242]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_242]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_242]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_242]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_242]
	at org.cloudburstmc.server.plugin.PluginClassLoader.findClass(PluginClassLoader.java:44) ~[Cloudburst.jar:?]
	at org.cloudburstmc.server.plugin.JavaPluginLoader.getClassByName(JavaPluginLoader.java:148) ~[Cloudburst.jar:?]
	at org.cloudburstmc.server.plugin.PluginClassLoader.findClass(PluginClassLoader.java:40) ~[Cloudburst.jar:?]
	at org.cloudburstmc.server.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28) ~[Cloudburst.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	at org.cloudburstmc.server.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:50) ~[Cloudburst.jar:?]
	at org.cloudburstmc.server.plugin.PluginManager.loadPlugin(PluginManager.java:95) ~[Cloudburst.jar:?]
	at org.cloudburstmc.server.plugin.PluginManager.loadPlugins(PluginManager.java:259) ~[Cloudburst.jar:?]
	at org.cloudburstmc.server.plugin.PluginManager.loadPlugins(PluginManager.java:127) ~[Cloudburst.jar:?]
	at org.cloudburstmc.server.plugin.PluginManager.loadPlugins(PluginManager.java:119) ~[Cloudburst.jar:?]
	at org.cloudburstmc.server.plugin.PluginManager.loadPlugins(PluginManager.java:115) ~[Cloudburst.jar:?]
	at org.cloudburstmc.server.Server.boot(Server.java:498) ~[Cloudburst.jar:?]
	at org.cloudburstmc.server.Nukkit.main(Nukkit.java:146) ~[Cloudburst.jar:?]
Caused by: java.lang.ClassNotFoundException: cn.nukkit.plugin.PluginBase
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
	at org.cloudburstmc.server.plugin.PluginClassLoader.findClass(PluginClassLoader.java:44) ~[Cloudburst.jar:?]
	at org.cloudburstmc.server.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28) ~[Cloudburst.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	... 23 more
2020-08-17 12:32:54.734 [main] INFO  - Stopping other threads

**Checklist**:

- [X] I included a `/debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of Nukkit
- [X] I Made sure the bug/error is not caused by a plugin

**Comment by SupremeMortal** [comment]
Nukkit plugins are not compatible

**Comment by Jaantheman** [comment]
Oh

**Comment by Jaantheman** [comment]
I did not know
